### ISSUE TITLE
State store not stopped when stopConsumer() called

### ISSUE THREAD

**Issue by GoldFlsh** [Raynos/leaked-handles#2]
Hello, I am running into an issue where when I run my application in jest connecting to a local instance of kinesis (re: Kinesalite). However, the issue I am seeing is that it detects open handles even when `stopConsumer()` is called before the end of a test.  

I've isolated this just to when lifion-kinesis is set to consume, so I know the issue is when using this library. 

My test is set up in this way ->
beforeAll(start kinesalite/dynalite) -> test(startConsumer -> stop Consumer) -> afterAll(stop kinesalite/dynalite)

When I run with https://github.com/Raynos/leaked-handles it checks what's still open and I get the following output - 

```

no of handles 4

....

  console.error
    2020-05-27T13:32:43-0500 <warn> dynamodb-client.js:135 (Object.onRetry) Trying to recover from AWS.DynamoDB error…
        - Message: connect ECONNREFUSED 127.0.0.1:52005
        - Request ID: undefined
        - Code: NetworkingError (undefined)
        - Table: local-dynamodb-component-test

      at transport (../node_modules/tracer/lib/console.js:87:13)
      at ../node_modules/tracer/lib/console.js:72:3
          at Array.forEach (<anonymous>)
      at logMain (../node_modules/tracer/lib/console.js:71:19)
      at Object._self.<computed> [as warn] (../node_modules/tracer/lib/console.js:149:12)
      at Object.onRetry (../node_modules/lifion-kinesis/lib/dynamodb-client.js:135:16)
      at onError (../node_modules/async-retry/lib/index.js:33:17)
```

**Comment by GoldFlsh** [comment]
Wrong repo, sorry.
